### ISSUE TITLE
call to set backup reserve level fails; errors in HA log

### ISSUE THREAD

**Issue by ChrisJ60** [alandtse/tesla#1125]
### Is there an existing issue for this?

- [x] I have searched both the existing open issues & recently closed issues and did not find a duplicate of this issue.

### Version of the Tesla component

3.25.0

### Version of the Powerwall Gateway software

25.18.4 b6b41ca8

### Model

2

### Current Behavior

(Very) occasionally a call to set the powerful backup reserve level fails and generates errors in the HA log. This aborts the automation that is running which then leads to other consequences. This same code is executed every day at the same time and in 99.9% of cases it works just fine but occasionally this failure occurs.

### Expected Behavior

 I don't know what causes the failure but I think it needs to be handled better to allow the automation that calls this function to continue rather than be aborted.

### Debug logs

```true
Since the issue is very infrequent I don;t have debug logs, but here are the relevant messages from the HA log when the error occurred last night. The value being passed (i.e. the value to set the reserve to) is, in this case, 100.

2025-07-19 04:00:00.701 ERROR (MainThread) [homeassistant.components.automation.pw_force_charge_set_backup_reserve_to_100_at_23_30] PW OFF-PEAK CHARGING: Set Backup Reserve to maximum off-peak charge level during off-peak period: If at step 2: If at step 1: If at step 1: Error executing script. Unexpected error for call_service at pos 1: 'code'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 524, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1012, in _async_step_call_service
    response_data = await self._async_run_long_action(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<9 lines>...
    )
    ^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 624, in _async_run_long_action
    return await long_task
           ^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2799, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2842, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1011, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
        hass, entity, func, data, call.context
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1083, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/number/__init__.py", line 122, in async_set_value
    await entity.async_set_native_value(native_value)
  File "/config/custom_components/tesla_custom/number.py", line 125, in async_set_native_value
    await self._energysite.set_reserve_percent(value)
  File "/usr/local/lib/python3.13/site-packages/teslajsonpy/energy.py", line 219, in set_reserve_percent
    if data and data["response"]["code"] == 201:
                ~~~~~~~~~~~~~~~~^^^^^^^^
KeyError: 'code'
```

**Comment by sandyman44** [comment]
I'm getting almost identical error message . all attempts to use HA to change backup reserve fail for me now.
`Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 258, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    )
    ^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2799, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2842, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1011, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
        hass, entity, func, data, call.context
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1083, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/number/__init__.py", line 122, in async_set_value
    await entity.async_set_native_value(native_value)
  File "/config/custom_components/tesla_custom/number.py", line 125, in async_set_native_value
    await self._energysite.set_reserve_percent(value)
  File "/usr/local/lib/python3.13/site-packages/teslajsonpy/energy.py", line 219, in set_reserve_percent
    if data and data["response"]["code"] == 201:
                ~~~~~~~~~~~~~~~~^^^^^^^^`

**Comment by ChrisJ60** [comment]
Yes, now that I look at it in more detail my HA is also now unable to change the backup reserve; all attempts fail with the above error. Since nothing has changed for me on the HA side (no HA updates, no integration updates) nor has my Powerwall itself received a firmware update within the past several days this would seem to be an issue with the Tesla API. I am able to change the reserve via the Tesla app.

**Comment by sandyman44** [comment]
> Yes, now that I look at it in more detail my HA is also now unable to change the backup reserve; all attempts fail with the above error. Since nothing has changed for me on the HA side (no HA updates, no integration updates) nor has my Powerwall itself received a firmware update within the past several days this would seem to be an issue with the Tesla API. I am able to change the reserve via the Tesla app.

for a while I thought that the other settings that can be changed by this integration (operation mode, grid charge, energy export) weren't working either, but have just tested them all several times and I'm pretty sure they are.

when I try to run a manual change to backup reserve from the UI, I get a small popup "failed to perform the action number/set_value.'code'

**Comment by ChrisJ60** [comment]
It looks like the Tesla API response to the command to change the backup reserve has changed and no longer includes a component called "code". As a temporary mitigation you can edit the file '/usr/local/lib/python3.13/site-packages/teslajsonpy/energy.py' in your HA instance (keep a backup copy!) and change the lines around 218-219 as follows:

#        if data and data["response"]["code"] == 201:
#            self._site_config.update({"backup_reserve_percent": value})
        self._site_config.update({"backup_reserve_percent": value})

then restart HA. That will restore the ability to change the backup reserve but it also no longer checks to see if the call encounters any errors (so it is not a long term fix). Hopefully @alandtse will be able to deliver an actual fix fairly quickly.

**Comment by sandyman44** [comment]
thanks for quickly digging into a fix, your obviously much more of a coder than me. I don't have a python3.13 directory at all in /usr/local/lib though. nor do I have an energy.py in config/custom_components/tesla_custom (which is where I thought this integration put stuff) if I have to go deeper than that I will start to get lost.

**Comment by ChrisJ60** [comment]
@skipishere 

> Feel free to make a PR with that as the fix, that way people can review it and decide if it's the right fix or not

I have no idea where to find the source of teslajsonpy. 

Strangely, when I enabled debug logging I saw that the response for that command does (now) include a 'code' element (though with a value of '200' not '201'. My guess is that there was a temporary issue with the Tesla API which has now been resolved. Nonetheless I think the code in energy.py should be updated to be:

        if data and ( data["response"]["code"] == 201 or data["response"]["code"] == 200 ):
            self._site_config.update({"backup_reserve_percent": value})

When I updated my copy with the code it now works fine. The old (original) code now works **some of the time but not always**. 

In fact I think that really this check should be to verify that the result code is 3 digits and the first digit is '2' and if so consider it successful (since any 2xx http status code indicates success. As I'm not a python programmer I will leave that to someone who is to consider / implement.

**Comment by sandyman44** [comment]
I don't even have a teslajsonpy. this is baffling. the directory referred to in the log  "/usr/local/lib/python3.13/site-packages/teslajsonpy/energy.py" simply doesn't exist. Under /usr/local/lib there is nothing.

**Comment by amanensia** [comment]
Seeing the same behaviour here.  Interestingly (or not) in my case the change to backup reserve level does succeed in changing the value, although the raised error then causes the automation to halt.  I've worked around it by re-ordering my automation to have this as the final step.

**Comment by ChrisJ60** [comment]
> Seeing the same behaviour here. Interestingly (or not) in my case the change to backup reserve level does succeed in changing the value, although the raised error then causes the automation to halt. I've worked around it by re-ordering my automation to have this as the final step.

Yes, that was actually what alerted me to the issue this morning. Sadly my automations are a bit complex so a simple re-ordering of steps cannot avoid the issue for me so I had to resort to 'continue_on_error: true'. And yes you are right; the change to the reserve value does take effect (though it may not then be selected in the HA UI). It was the response from the Tesla API that then caused the error to be thrown which in turn stopped the automation.

**Comment by ChrisJ60** [comment]
> I don't even have a teslajsonpy. this is baffling. the directory referred to in the log "/usr/local/lib/python3.13/site-packages/teslajsonpy/energy.py" simply doesn't exist. Under /usr/local/lib there is nothing.

That is indeed very strange. I cannot explain it... What install method do you use for HA? Mine is running in a docker container.

**Comment by skipishere** [comment]
Just taken a look now I'm home, `energy.py` is from part of https://github.com/zabuldon/teslajsonpy and the line your referencing is [219](https://github.com/zabuldon/teslajsonpy/blob/3123079b3b04adc2eec6a581c9f69422056b2ebe/teslajsonpy/energy.py#L219)

As far as I can see, eregy.py is the only place in the code that has this style of check (and like @ChrisJ60 says, any http 2xx should ideally be treated as success)

If anyone fancies raising an issue in https://github.com/zabuldon/teslajsonpy and making a fix, in theory once that's released this repo can then update it's dependency on it

**Comment by amanensia** [comment]
> > Seeing the same behaviour here. Interestingly (or not) in my case the change to backup reserve level does succeed in changing the value, although the raised error then causes the automation to halt. I've worked around it by re-ordering my automation to have this as the final step.
> 
> Yes, that was actually what alerted me to the issue this morning. Sadly my automations are a bit complex so a simple re-ordering of steps cannot avoid the issue for me so I had to resort to 'continue_on_error: true'. And yes you are right; the change to the reserve value does take effect (though it may not then be selected in the HA UI). It was the response from the Tesla API that then caused the error to be thrown which in turn stopped the automation.

Did _continue_on_error: true_ work for you?  I'd tried that as well but it didn't work, so I assumed the error being thrown wasn't in the correct format to be picked up by HA.  Maybe I did it wrong, I'm very new to this stuff.

**Comment by amanensia** [comment]
Indulge a newbie here - what's teslajsonpy?  Is that another set of source code that this integration relies on?

**Comment by ChrisJ60** [comment]
> Indulge a newbie here - what's teslajsonpy? Is that another set of source code that this integration relies on?

Yes, exactly that.

**Comment by ChrisJ60** [comment]
> [@skipishere](https://github.com/skipishere)
> 
> > If anyone fancies raising an issue in https://github.com/zabuldon/teslajsonpy and making a fix, in theory once that's released this repo can then update its dependency on it
> 
> I've raised an issue there and proposed a code fix...
> 
> ```
>     if data and data["response"] and date["response"]["code"] and
>         (len(data["response"]["code"] == 3) and (data["response"]["code"][:1] == 2):
> ```
> 
> Let's see if I get any response. If not then I will raise a PR.

Hmm, actually that code does not work (throws a syntax error). it seems that teslajsonpy is not reloaded when the Tesla Custom integration is reloaded only on a full HA restart. I guess I need to learn more python...

**Comment by skipishere** [comment]
Think you're a `)` short

**Comment by sandyman44** [comment]
how do I find teslajsonpy in my system and/or how would I install it and make this change? The github for it doesn't appear to contain that basic a level of information.  As mentioned, this integration is working so if it depends on that teslajsonpy I guess I must have it, but I have no idea where. I can't see any evidence of it in HACS. it doesn't exist at the directory referenced in the logs. I'm running HA OS 2025.7.2

**Comment by skipishere** [comment]
> how do I find teslajsonpy in my system and/or how would I install it and make this change? 

It's a dependency this repo has, in theory you should be able to find a `energy.py` file on your system but the correct fix here is to get it updated in the original repository and then we can update it here. Trying to manually apply a fix isn't normally recommended because if you make a mistake it can be a pain to correct yourself

**Comment by rob0101** [comment]
I noticed the same issue with the Teslapy scripts.

Also for me, I can no longer set a MRL above 80 now.   Tesla app, Netzero, TeslaOne, teslapy will all set the MRL to 80 when I try to set it higher.

I was using the MRL to force the PW to reserve the battery and use the grid temporarily.

**Comment by ChrisJ60** [comment]
> I noticed the same issue with the Teslapy scripts.
> 
> Also for me, I can no longer set a MRL above 80 now. Tesla app, Netzero, TeslaOne, teslapy will all set the MRL to 80 when I try to set it higher.
> 
> I was using the MRL to force the PW to reserve the battery and use the grid temporarily.

Yes, I just noticed the same issue overnight. Normally I set my system to 85% at midnight and then 100% at 04:30 to ensure it is 100% charged by the morning. That no longer works. As you note even the Tesla app has an issue; it appears to set the reserve higher when you first do it but in fact the reserve reverts back to 80% later on. Seems like Tesla are changing things, though why they are doing so I do not know. I will open a case with Tesla support about the app.

**Comment by ChrisJ60** [comment]
> Think you're a `)` short

Yes, that was a problem but Tesla seem to have made further changes now and it looks like the call no longer returns a code (as per the original issue) so the fix is somewhat moot. The test for the response needs to be removed altogether or changed radically.

**Comment by ChrisJ60** [comment]
> I've created a hack-fix pull request (that I tested on my own home assistant last night) until teslajsonpy is updated and is awaiting a code review.

Would you be willing to share that hack? I'd like to test it until a proper fix is implemented.

**Comment by sandyman44** [comment]
I've tried this fix - hand edited the number.py file - it has not worked for me. I no longer get the UI popup error when I  move the slider in the UI, but is not reliably changing the powerwall. The automation isn't running to completion either. I think I've seen it once (out of maybe 20 attempts?) change the powerwall setting, but its definitely not behaving properly

I've done a find on my entire system (at least I think I have) teslajsonpy and energy.py do not exist. Its HA OS on a dedicated PC.

like probably 99% of others I use this automation to force non-discharge and/or charge to increase when EV is charging and/or cheap import rate. Tesla beginning to annoy me here - good hardware but  let us decide when we want it charged or not.

**Comment by duffjp** [comment]
> how do I find teslajsonpy in my system and/or how would I install it and make this change? The github for it doesn't appear to contain that basic a level of information. As mentioned, this integration is working so if it depends on that teslajsonpy I guess I must have it, but I have no idea where. I can't see any evidence of it in HACS. it doesn't exist at the directory referenced in the logs. I'm running HA OS 2025.7.2

@sandyman44  I run in a docker system and it has a folder substructure that the dependencies sit within.  To find the correct file, I putty'd to my system and ran the following command

find / -name energy.py | grep /usr/local/lib/python3.13/site-packages/teslajsonpy/energy.py

**Comment by duffjp** [comment]
> > I use it for exactly the same purposes and it's working OK for me by just having the backup reserve as the final step. I get the failure message, but it reliably updates the value. Example UI setup below - I've got a few of these for different situations and they are all working OK.
> 
> thank you. in my case it wasn't the order, but the type of action. I did have a set number (upper one, now disabled) which worked until recently. I've changed it to the method you've used, and it works from the automation now.
> 
> <img alt="Image" width="1123" height="901" src="https://private-user-images.githubusercontent.com/80401234/468376926-45cb6feb-8f2e-4420-af57-5f792a3d183b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTMwMTQxMTAsIm5iZiI6MTc1MzAxMzgxMCwicGF0aCI6Ii84MDQwMTIzNC80NjgzNzY5MjYtNDVjYjZmZWItOGYyZS00NDIwLWFmNTctNWY3OTJhM2QxODNiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA3MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwNzIwVDEyMTY1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNkMWY2NjIzY2Q1YzQ1MjJjYjIxM2VmOTY2ZDQyYzFhMmQ0ZGQ3MDEwOWJjM2M4NWIxYmZiZmU1MGFiZDE2ZTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.E-oWGNceGsrx7OXVMwcagUrXxOz-tV_vv2v-caKyT0w">

Ah, interesting.  I am using the Number Set approach, which is now working for me again.  I might look at switching to Set value later and see if that removes any dependencies on validation steps which could fail.

**Comment by sandyman44** [comment]
> > how do I find teslajsonpy in my system and/or how would I install it and make this change? The github for it doesn't appear to contain that basic a level of information. As mentioned, this integration is working so if it depends on that teslajsonpy I guess I must have it, but I have no idea where. I can't see any evidence of it in HACS. it doesn't exist at the directory referenced in the logs. I'm running HA OS 2025.7.2
> 
> [@sandyman44](https://github.com/sandyman44) I run in a docker system and it has a folder substructure that the dependencies sit within. To find the correct file, I putty'd to my system and ran the following command
> 
> find / -name energy.py | grep /usr/local/lib/python3.13/site-packages/teslajsonpy/energy.py

that is my point. I use the HA OS on dedicated pc. Said file and in fact directory, do not exist.
 I'm not a coder (am a networking geek) but I do have 30 years experience on linux (slackware 1.0...).

<img width="945" height="463" alt="Image" src="https://github.com/user-attachments/assets/c76d360c-cb9d-4225-b115-a9090f5baee2" />

**Comment by ChrisJ60** [comment]
> Is it worth re-wording this - it's a 100% failure rate now, no? Just in case the description leads to it not being considered important.

@amanensia I have modified the wording but of course since I first logged the issue things have moved on and the problem is not actually in this integration but rather in the teslajsonpy library that this integration uses. The fix needs to be applied there.

**Comment by upperdarkness** [comment]
@sandyman44 run this command from the HAOS command line:
docker exec -it homeassistant bash

that will connect you to the docker container where the python dependencies are downloaded to. Then you can:
cd /usr/local/lib/python3.13/site-packages/teslajsonpy/
and you will find energy.py
Then you'll need to master the dark art of using vi to edit energy.py
from memory:
vi energy.py
then hit the escape key and type :g219 and press enter
use the arrow keys to find the 2 lines you need to comment out. Press lowercase i to enter insert mode
enter the # to comment out the two lines. Then copy the last line and paste it to the correct location. Indentation is important in python.
When done, hit the escape and enter :wq to save and exit the editor. Then restart HA and it should work.

**Comment by kalevalan** [comment]
> > [@sandyman44](https://github.com/sandyman44) run this command from the HAOS command line: docker exec -it homeassistant bash
> 
> <img alt="Image" width="410" height="51" src="https://private-user-images.githubusercontent.com/80401234/468399540-feabd6dd-d05d-4952-9b68-e357332211dd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTMwNjY5OTksIm5iZiI6MTc1MzA2NjY5OSwicGF0aCI6Ii84MDQwMTIzNC80NjgzOTk1NDAtZmVhYmQ2ZGQtZDA1ZC00OTUyLTliNjgtZTM1NzMzMjIxMWRkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA3MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwNzIxVDAyNTgxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQwNWNhOTA1MGY5MmZlOTE3M2ZjYmE5YjNhNjdhNTIyZDg1MzQ2NjBlNDlhYTEwZDZlMDBmZmU2NGFkYmFkYTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.lmDKrOOc85wGNRk0_yvVlm1jnJU1oMYYsCSIf0RKI1Q">
> 
> I don't know how HAOS is put together but docker isn't there either.
> 
> I'm fine with using vi by the way - used to be the only editor... I just can't find this damn file!

@sandyman44 

I had to download Advanced SSH & Web terminal from Addons to access docker. Install that, but before running it, untick protected mode. From there you can follow @upperdarkness very good instructions.

Thanks @ChrisJ60 for the improved code, my system is now running completely normal again after I made your changes to energy.py

**Comment by ChrisJ60** [comment]
I've created a PR in the teslajsonpy project to try to get my fix merged into that.

**Comment by sandyman44** [comment]
> 
> I had to download Advanced SSH & Web terminal from Addons to access docker. Install that, but before running it, untick protected mode. From there you can follow [@upperdarkness](https://github.com/upperdarkness) very good instructions.
> 

thanks. that was the answer. I don't understand how the docker virtualisation layers work in HA, how can directories that matter be just not there?!?! One would assume that by using the HA official terminal add-on one was ssh-ing into HA, but clearly not. Anyway with the "advanced" version of the terminal app, and un-protected mode, I can now run the docker command and I can see lots of stuff in /usr/local/lib including python3.13. I will tackle finding and editing the energy.py file later.

as a side note, only using the hack to number.py, my automation to set to 100% worked last night, using a "set device value" action.

**Comment by meow4agreencard** [comment]
> > I had to update the energy.py code to say:
> > > ```
> > >    if data and ( data["response"]["Code"] == 201 or data["response"]["Code"] == 200 ):
> > >        self._site_config.update({"backup_reserve_percent": value})
> > > ```
> > 
> > 
> > Again, note the capital C.
> > Obviously if the API gets reverted to lower case 'c' the code will again be wrong
> 
> Yes indeed. My latest proposed fix in energy.py, which I have been testing and so far works fine subject to the new Tesla restriction whereby you cannot set the reserve to any value in the range 81 - 99, is as follows:
> 
> `if data and data["response"] and data["response"]["Code"] and (len(str(data["response"]["Code"])) == 3) and (str(data["response"]["Code"])[:1] == "2"):`
> 
> I've proposed this on the Issues section for teslajsonpy but I have no idea if they will implement it or not.

I was testing out the workaround and I was getting errors trying to start the integration with this code.

This one works:
> > >    if data and ( data["response"]["Code"] == 201 or data["response"]["Code"] == 200 ):
> > >        self._site_config.update({"backup_reserve_percent": value})

**Comment by billraff** [comment]
If someone could provide a screenshot of the relevant lines they have commented out and the new lines below them it might help me. I get an error every time I restart and it always points to the lines I have added. My vi-fu is sorely lacking.

**Comment by ChrisJ60** [comment]
> If someone could provide a screenshot of the relevant lines they have commented out and the new lines below them it might help me. I get an error every time I restart and it always points to the lines I have added. My vi-fu is sorely lacking.

Here you go. The indentation is critical coz Python really v=cares about that (yeah, I know...)

<img width="1133" height="232" alt="Image" src="https://github.com/user-attachments/assets/33770452-b2d8-4bd0-a123-a0200de668e1" />

**Comment by skipishere** [comment]
The PR that will help fix this is https://github.com/zabuldon/teslajsonpy/pull/487

**Comment by kalevalan** [comment]
Unfortunately my system is now generating the same error again. I'm not sure if it is because the modified code was overwritten by something, or if Tesla have made more changes to the API responses. Has anyone else had this happen?

**Comment by SalisburyLad** [comment]
Just to add to this, the last two days, although the reserve has updated in HA and on the Tesla app (dispite the error), my powerwall did not switch from importing from the grid as it should: self-powered & 5% reserve. Tweaking the reserve value in the Tesla app did the trick and the powerwall immediately started supplying the house but the app did show the reserve being 5%!

**Comment by SalisburyLad** [comment]
> > Just to add to this, the last two days, although the reserve has updated in HA and on the Tesla app (dispite the error), my powerwall did not switch from importing from the grid as it should: self-powered & 5% reserve. Tweaking the reserve value in the Tesla app did the trick and the powerwall immediately started supplying the house but the app did show the reserve being 5%!
> 
> Do you have an automation that tries to modify Operation mode AFTER Backup reserve? I swapped things around so my automation script modifies Operation mode THEN Backup reserve. It still throws an error and the script stops, but all actions are completed.

No, it is the last action of the automation.

<img width="776" height="735" alt="Image" src="https://github.com/user-attachments/assets/4cb9dbfb-b6e2-4d97-abe2-b64aaed25272" />

**Comment by timpauladams** [comment]
So it’s been closed but still not fixed, how come ?

Thx

**Comment by skipishere** [comment]
@timpauladams because it was fixed just wasn't yet released

**Comment by timpauladams** [comment]
Just updated Tesla custom app to 3.25.2
But not resolved 

/

![Image](https://github.com/user-attachments/assets/8cf40c97-c951-4199-b5a5-c0c1851ae7d2)

**Comment by skipishere** [comment]
> Just updated Tesla custom app to 3.25.2
> But not resolved 
> 
> /
> 
> ![Image](https://github.com/user-attachments/assets/8cf40c97-c951-4199-b5a5-c0c1851ae7d2)

Works for me, it would be best if you opened a new issue and include what you are using and applicable logs

**Comment by amanensia** [comment]
Works for me too.

**Comment by timpauladams** [comment]
A second reboot has resolved 

Thx
