### ISSUE TITLE
KeyError: 'load_power' No longer getting data from Solar Panels

### ISSUE THREAD

**Issue by ylwmamba** [alandtse/tesla#254]
## Version of the custom_component

v2.4.0

## Describe the bug

Since updating to latest version, I am no longer getting data from my solar panels. I do have a Solar City inverter but I was getting the data prior to this version and I do get the data from the Tesla app. I uninstalled and reinstalled the integration and generated a new token but still no data.

## Debug log

This error originated from a custom integration.

Logger: homeassistant
Source: custom_components/tesla_custom/tesla_device.py:129
Integration: Tesla Custom Integration (documentation, issues)
First occurred: 9:31:55 AM (244 occurrences)
Last logged: 10:14:30 AM

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 151, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 283, in _async_refresh
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 110, in async_update_listeners
    update_callback()
  File "/config/custom_components/tesla_custom/tesla_device.py", line 129, in refresh
    self.tesla_device.refresh()
  File "/usr/local/lib/python3.10/site-packages/teslajsonpy/homeassistant/power.py", line 221, in refresh
    self.__load_power = data["load_power"]
KeyError: 'load_power'

**Comment by alandtse** [comment]
@shred86 can you please handle? Looks like the key may not exist

**Comment by shred86** [comment]
@ylwmamba Are you seeing three sensors created for your Tesla solar system? There should be a solar power, grid power and load power sensor. The grid and load power you can just ignore or delete if you don't have a Neurio energy monitoring device with your install, which it appears you don't based on the debug log. However, the solar power sensor should still be working since it's getting the data from the same place it was before. Do you happen to have any other errors in your logs?

I'll submit a PR to fix that key error though for the load and grid power sensors.

**Comment by ylwmamba** [comment]
> @ylwmamba Are you seeing three sensors created for your Tesla solar system? There should be a solar power, grid power and load power sensor. The grid and load power you can just ignore or delete if you don't have a Neurio energy monitoring device with your install, which it appears you don't based on the debug log. However, the solar power sensor should still be working since it's getting the data from the same place it was before. Do you happen to have any other errors in your logs?
> 
> I'll submit a PR to fix that key error though for the load and grid power sensors.

I'm only seeing 2 sensors now. I previously had one with the last version which was the solar panel and it was no longer working after the update. After I deleted and reinstalled the integration, I'm only left with 2 sensors: grid and load power and they just show 0.

**Comment by shred86** [comment]
Hm, that's really strange. Would you mind trying to things:

1) Add the following to your HA configuration.yaml:

````
logger:
  default: critical
  logs:
    custom_components.tesla_custom: debug
    teslajsonpy: debug
````

Restart Home Assistant and check your logs. You should see something in there that looks like below. I'm just curious what that looks like.
````
2022-08-27 00:26:54.430 DEBUG (MainThread) [teslajsonpy.connection] 200: {"response":{"solar_power":820,"load_power":14272.7001953125,"grid_status":"Unknown","grid_services_active":false,"grid_power":13452.7001953125,"grid_services_power":0,"generator_power":0,"island_status":"island_status_unknown","storm_mode_active":false,"timestamp":"2022-08-26T17:26:55-07:00","wall_connectors":[]}}
````

2) Can you try reverting back to the previous version of this integration? You should be able to do it from HACS. I'm curious if the solar power sensor shows up.

**Comment by ylwmamba** [comment]
This is what it says in the log:

2022-08-26 17:36:43.640 DEBUG (MainThread) [teslajsonpy.connection] 200: {"response":{"solar_power":614,"timestamp":"2022-08-26T17:36:43-07:00","wall_connectors":null}}

I reverted back to 2.3.1 and everything is working as it was previously.

![image](https://user-images.githubusercontent.com/99165322/187008278-3612fb16-523c-4cdf-a02d-d527f259814b.png)

**Comment by shred86** [comment]
Thanks. Yeah, that's strange the solar panel sensor isn't show up. Nothing really changed in the code as far as how the sensors are initialized and where it's pulling data from. I did make a pull request to fix the KeyError issue for `load_power`. It basically just checks to see if you have a load meter (i.e. Neurio energy monitoring device) installed and if not, the load and grid power sensors won't be created. Once it gets merged, I'll submit a PR to bump the version of this integration and maybe a beta version can get pushed out first to have some folks test. I don't know if it will fix your issue but there are some fixes with how devices are named so perhaps it might.

**Comment by ylwmamba** [comment]
Sounds good. I'll keep it at v2.3.1 for now. Thank you for looking into it.

**Comment by shred86** [comment]
@ylwmamba v2.4.1 is available. It should fix this "load_power" KeyError in that you won't see a load or grid power sensor being created anymore if your setup doesn't have a load meter (Neurio energy monitoring device). I'm not sure if it will fix your solar panel sensor not showing up but it might. If it does not, can you please open another issue with any associated log messages and I'll try to keep troubleshooting.

**Comment by ylwmamba** [comment]
> @ylwmamba v2.4.1 is available. It should fix this "load_power" KeyError in that you won't see a load or grid power sensor being created anymore if your setup doesn't have a load meter (Neurio energy monitoring device). I'm not sure if it will fix your solar panel sensor not showing up but it might. If it does not, can you please open another issue with any associated log messages and I'll try to keep troubleshooting.

I updated to v2.4.1, at first it would not load so I had to delete and reinstall. It does not create the load or grid power sensor anymore but it is still showing my solar panel sensor as unavailable. I'll open another issue with the new log message.
