### ISSUE TITLE
Solar Sensors not updating because energy site number keeps on being refreshed

### ISSUE THREAD

**Issue by cprevoteau** [alandtse/tesla#274]
My solar sensors (load, grid, solar panel) have been working fine for more than a month but stopped being refreshed yesterday.
Upon restarting the Tesla custom integration in HA, I noticed a new set of 3 sensors being created and working fine for 10 to 30 minutes until they stopped being refreshed again. Same thing happens everytime I restart the integration, a new set of 3 sensors are being created and are working fine for 10 to 30 minutes
I checked the logs and noticed that the problem might come from the energysite being updated by Tesla.
See below in the logs, I restarted the integration around 6:47:07.
Issue reproduced in both 2.4.0 and 2.4.3.

Logs:
```text
2022-10-05 06:46:48.002 DEBUG (MainThread) [custom_components.tesla_custom] Running controller.update()
2022-10-05 06:46:48.002 DEBUG (MainThread) [teslajsonpy.controller] Get vehicles. Force: False Time: 20 Interval 60
2022-10-05 06:46:48.003 DEBUG (MainThread) [teslajsonpy.controller] Updating energysite 2252152663543514
2022-10-05 06:46:48.004 DEBUG (MainThread) [teslajsonpy.connection] Token expiration in 0:26:52
2022-10-05 06:46:48.005 DEBUG (MainThread) [teslajsonpy.connection] get: https://owner-api.teslamotors.com/api/1/energy_sites/2252152663543514/live_status {}
2022-10-05 06:46:48.184 DEBUG (MainThread) [teslajsonpy.connection] 404: {"response":null,"error":"not_found","error_description":""}
2022-10-05 06:46:48.185 DEBUG (MainThread) [teslajsonpy.controller] Exception:
api(('SITE_DATA',) {'path_vars': {'site_id': 2252152663543514}, 'wake_if_asleep': False})
2022-10-05 06:46:48.187 DEBUG (MainThread) [custom_components.tesla_custom] Finished fetching tesla_custom data in 0.186 seconds (success: True)
2022-10-05 06:46:58.006 DEBUG (MainThread) [custom_components.tesla_custom] Running controller.update()
2022-10-05 06:46:58.007 DEBUG (MainThread) [teslajsonpy.controller] Get vehicles. Force: False Time: 30 Interval 60
2022-10-05 06:46:58.008 DEBUG (MainThread) [teslajsonpy.controller] Updating energysite 2252152663543514
2022-10-05 06:46:58.008 DEBUG (MainThread) [teslajsonpy.connection] Token expiration in 0:26:42
2022-10-05 06:46:58.009 DEBUG (MainThread) [teslajsonpy.connection] get: https://owner-api.teslamotors.com/api/1/energy_sites/2252152663543514/live_status {}
2022-10-05 06:46:58.172 DEBUG (MainThread) [teslajsonpy.connection] 404: {"response":null,"error":"not_found","error_description":""}
2022-10-05 06:46:58.173 DEBUG (MainThread) [teslajsonpy.controller] Exception:
api(('SITE_DATA',) {'path_vars': {'site_id': 2252152663543514}, 'wake_if_asleep': False})
2022-10-05 06:46:58.173 DEBUG (MainThread) [custom_components.tesla_custom] Finished fetching tesla_custom data in 0.167 seconds (success: True)
2022-10-05 06:47:07.148 DEBUG (MainThread) [teslajsonpy.controller] Disconnecting controller.
2022-10-05 06:47:07.149 DEBUG (MainThread) [teslajsonpy.connection] Connection closed.
2022-10-05 06:47:07.149 DEBUG (MainThread) [custom_components.tesla_custom] Unloaded entry for XXX
2022-10-05 06:47:07.182 DEBUG (MainThread) [teslajsonpy.connection] Connecting with existing access token
2022-10-05 06:47:07.198 DEBUG (MainThread) [teslajsonpy.controller] 399 endpoints loaded
2022-10-05 06:47:07.199 DEBUG (MainThread) [teslajsonpy.connection] Token expiration in 0:26:33
2022-10-05 06:47:07.199 DEBUG (MainThread) [teslajsonpy.connection] get: https://owner-api.teslamotors.com/api/1/vehicles {}
2022-10-05 06:47:07.420 DEBUG (MainThread) [teslajsonpy.connection] 200: {"response":[],"count":0}
2022-10-05 06:47:07.421 DEBUG (MainThread) [teslajsonpy.connection] Token expiration in 0:26:33
2022-10-05 06:47:07.421 DEBUG (MainThread) [teslajsonpy.connection] get: https://owner-api.teslamotors.com/api/1/products {}
2022-10-05 06:47:07.539 DEBUG (MainThread) [teslajsonpy.connection] 200: {"response":[{"energy_site_id":2252144902381336,"resource_type":"solar","id":"XXX","asset_site_id":"XXX","solar_power":0,"solar_type":"pv_panel","storm_mode_enabled":null,"powerwall_onboarding_settings_set":null,"sync_grid_alert_enabled":false,"breaker_alert_enabled":false,"components":{"battery":false,"solar":true,"solar_type":"pv_panel","grid":true,"load_meter":true,"market_type":"residential"}}],"count":1}
2022-10-05 06:47:07.540 DEBUG (MainThread) [teslajsonpy.connection] Token expiration in 0:26:33
2022-10-05 06:47:07.540 DEBUG (MainThread) [teslajsonpy.connection] get: https://owner-api.teslamotors.com/api/1/energy_sites/2252144902381336/site_info {}
2022-10-05 06:47:08.004 DEBUG (MainThread) [teslajsonpy.connection] 200: {"response":{"id":"0829675f-d269-42c0-8956-86ced30f4687","site_number":"XXX","installation_date":"2022-07-08T16:57:00Z","user_settings":{"storm_mode_enabled":null,"powerwall_onboarding_settings_set":null,"sync_grid_alert_enabled":false,"breaker_alert_enabled":false},"components":{"solar":true,"solar_type":"pv_panel","battery":false,"grid":true,"backup":false,"gateway":"gateway_type_none","load_meter":true,"tou_capable":false,"storm_mode_capable":false,"flex_energy_request_capable":false,"car_charging_data_supported":false,"off_grid_vehicle_charging_reserve_supported":false,"vehicle_charging_performance_view_enabled":false,"vehicle_charging_solar_offset_view_enabled":false,"battery_solar_offset_view_enabled":false,"energy_service_self_scheduling_enabled":true,"configurable":false,"grid_services_enabled":false},"installation_time_zone":"America/Denver","geolocation":{"latitude":XXX,"longitude":XXX},"address":{"address_line1":"XXX","city":"XXX","state":"XXX","zip":"XXX","country":"XXX"}}}
2022-10-05 06:47:08.005 DEBUG (MainThread) [teslajsonpy.controller] Get vehicles. Force: False Time: 1 Interval 60
2022-10-05 06:47:08.005 DEBUG (MainThread) [teslajsonpy.controller] Updating energysite 2252144902381336
2022-10-05 06:47:08.006 DEBUG (MainThread) [teslajsonpy.connection] Token expiration in 0:26:32
2022-10-05 06:47:08.007 DEBUG (MainThread) [teslajsonpy.connection] get: https://owner-api.teslamotors.com/api/1/energy_sites/2252144902381336/live_status {}
2022-10-05 06:47:08.124 DEBUG (MainThread) [teslajsonpy.connection] 200: {"response":{"solar_power":0,"load_power":316.3399963378906,"grid_status":"Unknown","grid_services_active":false,"grid_power":316.3399963378906,"grid_services_power":0,"generator_power":0,"island_status":"island_status_unknown","storm_mode_active":false,"timestamp":"2022-10-05T06:47:08-06:00","wall_connectors":[]}}
2022-10-05 06:47:08.125 DEBUG (MainThread) [custom_components.tesla_custom] Connected to the Tesla API
2022-10-05 06:47:08.126 DEBUG (MainThread) [custom_components.tesla_custom] Running controller.update()
2022-10-05 06:47:08.126 DEBUG (MainThread) [teslajsonpy.controller] Get vehicles. Force: False Time: 1 Interval 60
2022-10-05 06:47:08.127 DEBUG (MainThread) [teslajsonpy.controller] Updating energysite 2252144902381336
2022-10-05 06:47:08.128 DEBUG (MainThread) [teslajsonpy.connection] Token expiration in 0:26:32
2022-10-05 06:47:08.129 DEBUG (MainThread) [teslajsonpy.connection] get: https://owner-api.teslamotors.com/api/1/energy_sites/2252144902381336/live_status {}
2022-10-05 06:47:08.263 DEBUG (MainThread) [teslajsonpy.connection] 200: {"response":{"solar_power":0,"load_power":316.3399963378906,"grid_status":"Unknown","grid_services_active":false,"grid_power":316.3399963378906,"grid_services_power":0,"generator_power":0,"island_status":"island_status_unknown","storm_mode_active":false,"timestamp":"2022-10-05T06:47:08-06:00","wall_connectors":[]}}
2022-10-05 06:47:08.264 DEBUG (MainThread) [custom_components.tesla_custom] Finished fetching tesla_custom data in 0.138 seconds (success: True)
```

**Comment by redwood996** [comment]
Same problem happen to me.

**Comment by cprevoteau** [comment]
The problem is not reproduced anymore. Looks like a glitch on Tesla API side which has been corrected. Can be closed

**Comment by redwood996** [comment]
> The problem is not reproduced anymore. Looks like a glitch on Tesla API side which has been corrected. Can be closed

Unfortunately I'm still seeing this issue. It works for some time, and not updating again...
