### ISSUE TITLE
Issue with TeslaMate and multiple cars

### ISSUE THREAD

**Issue by Megabytemb** [alandtse/tesla#581]
> 
> I just made a pull request in teslajsonpy to fix this. [zabuldon/teslajsonpy#404](https://github.com/zabuldon/teslajsonpy/pull/404)
> 
> will get this into the integration soon

Excellent. Any thoughts as to why I can never get data for car 1 but I do for car 2. I can see that it has subscribed to both:
```
2023-04-25 00:30:17.384 INFO (MainThread) [custom_components.tesla_custom.teslamate] Setting up MQTT subs for Teslamate
2023-04-25 00:30:17.384 INFO (MainThread) [custom_components.tesla_custom.teslamate] Un-subbing from MQTT Topics.
2023-04-25 00:30:17.400 INFO (MainThread) [custom_components.tesla_custom.teslamate] Subscribed to topic: teslamate/cars/1/#
2023-04-25 00:30:17.438 INFO (MainThread) [custom_components.tesla_custom.teslamate] Subscribed to topic: teslamate/cars/2/#
2023-04-25 00:30:17.616 INFO (MainThread) [custom_components.tesla_custom.teslamate] Setting latitude from MQTT
2023-04-25 00:30:17.633 INFO (MainThread) [custom_components.tesla_custom.teslamate] Setting odometer from MQTT
2023-04-25 00:30:17.655 INFO (MainThread) [custom_components.tesla_custom.teslamate] Setting battery_level from MQTT
2023-04-25 00:30:17.665 INFO (MainThread) [custom_components.tesla_custom.teslamate] Setting longitude from MQTT
2023-04-25 00:30:17.672 INFO (MainThread) [custom_components.tesla_custom.teslamate] Setting usable_battery_level from MQTT
2023-04-25 00:30:17.678 INFO (MainThread) [custom_components.tesla_custom.teslamate] Setting outside_temp from MQTT
2023-04-25 00:30:17.697 INFO (MainThread) [custom_components.tesla_custom.teslamate] Setting inside_temp from MQTT
2023-04-25 00:30:17.705 INFO (MainThread) [custom_components.tesla_custom.teslamate] Setting tpms_pressure_rl from MQTT
2023-04-25 00:30:17.722 INFO (MainThread) [custom_components.tesla_custom.teslamate] Setting tpms_pressure_fr from MQTT
2023-04-25 00:30:17.728 INFO (MainThread) [custom_components.tesla_custom.teslamate] Setting charger_actual_current from MQTT
2023-04-25 00:30:17.736 INFO (MainThread) [custom_components.tesla_custom.teslamate] Setting time_to_full_charge from MQTT
2023-04-25 00:30:17.770 INFO (MainThread) [custom_components.tesla_custom.teslamate] Setting sentry_mode from MQTT
2023-04-25 00:30:17.775 INFO (MainThread) [custom_components.tesla_custom.teslamate] Setting charger_voltage from MQTT
2023-04-25 00:30:17.781 INFO (MainThread) [custom_components.tesla_custom.teslamate] Setting charge_limit_soc from MQTT
2023-04-25 00:30:17.786 INFO (MainThread) [custom_components.tesla_custom.teslamate] Setting heading from MQTT
2023-04-25 00:30:17.795 INFO (MainThread) [custom_components.tesla_custom.teslamate] Setting locked from MQTT
2023-04-25 00:30:17.802 INFO (MainThread) [custom_components.tesla_custom.teslamate] Setting charge_energy_added from MQTT
2023-04-25 00:30:17.808 INFO (MainThread) [custom_components.tesla_custom.teslamate] Setting tpms_pressure_rr from MQTT
2023-04-25 00:30:17.812 INFO (MainThread) [custom_components.tesla_custom.teslamate] Setting tpms_pressure_fl from MQTT
2023-04-25 00:30:17.819 INFO (MainThread) [custom_components.tesla_custom.teslamate] Setting charger_power from MQTT
2023-04-25 00:30:17.824 INFO (MainThread) [custom_components.tesla_custom.teslamate] Setting is_climate_on from MQTT
2023-04-25 00:30:17.831 INFO (MainThread) [custom_components.tesla_custom.teslamate] Setting speed from MQTT
```

_Originally posted by @drjjr2 in https://github.com/alandtse/tesla/issues/564#issuecomment-1521707068_

**Comment by drjjr2** [comment]
OK, done. 
Here's what I see when on startup.

```
2023-04-25 09:02:23.430 INFO (MainThread) [custom_components.tesla_custom.teslamate] Setting up MQTT subs for Teslamate
2023-04-25 09:02:23.431 INFO (MainThread) [custom_components.tesla_custom.teslamate] Un-subbing from all MQTT Topics.
2023-04-25 09:02:23.431 INFO (MainThread) [custom_components.tesla_custom.teslamate] Un-subbed from all MQTT Topics.
2023-04-25 09:02:23.442 DEBUG (MainThread) [custom_components.tesla_custom.teslamate] Got car ID. VIN:5YJ3E1EC3PFxxxxxx TeslamateID: 1
2023-04-25 09:02:23.443 DEBUG (MainThread) [custom_components.tesla_custom.teslamate] Setting up MQTT Sub for VIN:5YJ3E1EC3PFxxxxxx TelsaMateID:1
2023-04-25 09:02:23.443 DEBUG (MainThread) [custom_components.tesla_custom.teslamate] MQTT Topic: teslamate/cars/1/#
2023-04-25 09:02:23.444 INFO (MainThread) [custom_components.tesla_custom.teslamate] Subscribed to topic: teslamate/cars/1/#
2023-04-25 09:02:23.444 DEBUG (MainThread) [custom_components.tesla_custom.teslamate] Got car ID. VIN:7SAYGDEE8PAxxxxxx TeslamateID: 2
2023-04-25 09:02:23.445 DEBUG (MainThread) [custom_components.tesla_custom.teslamate] Setting up MQTT Sub for VIN:7SAYGDEE8PAxxxxxx TelsaMateID:2
2023-04-25 09:02:23.445 DEBUG (MainThread) [custom_components.tesla_custom.teslamate] MQTT Topic: teslamate/cars/2/#
2023-04-25 09:02:23.446 INFO (MainThread) [custom_components.tesla_custom.teslamate] Subscribed to topic: teslamate/cars/2/#
2023-04-25 09:02:23.446 DEBUG (MainThread) [custom_components.tesla_custom.teslamate] Completed watch_cars
2023-04-25 09:02:23.446 DEBUG (MainThread) [custom_components.tesla_custom] Connected to the Tesla API
2023-04-25 09:02:23.536 DEBUG (MainThread) [custom_components.tesla_custom.teslamate] Got car ID. VIN:5YJ3E1EC3PFxxxxxx TeslamateID: 1
2023-04-25 09:02:23.537 DEBUG (MainThread) [custom_components.tesla_custom.teslamate] Got car ID. VIN:7SAYGDEE8PAxxxxxx TeslamateID: 2
2023-04-25 09:02:23.539 DEBUG (MainThread) [custom_components.tesla_custom] Running controller.update()
2023-04-25 09:02:23.560 DEBUG (MainThread) [custom_components.tesla_custom] Running controller.update()
2023-04-25 09:02:24.218 DEBUG (MainThread) [custom_components.tesla_custom] Finished fetching tesla_custom data in 0.679 seconds (success: True)
2023-04-25 09:02:24.472 DEBUG (MainThread) [custom_components.tesla_custom.teslamate] Got car ID. VIN:7SAYGDEE8PAxxxxxx TeslamateID: 2
2023-04-25 09:02:24.473 DEBUG (MainThread) [custom_components.tesla_custom.teslamate] MQTT Topic Recieved: teslamate/cars/2/rated_battery_range_km
2023-04-25 09:02:24.473 INFO (MainThread) [custom_components.tesla_custom.teslamate] Got rated_battery_range_km from MQTT for VIN:7SAYGDEE8PAxxxxxx | TeslsMateID:2
2023-04-25 09:02:24.479 DEBUG (MainThread) [custom_components.tesla_custom.teslamate] Got car ID. VIN:7SAYGDEE8PAxxxxxx TeslamateID: 2
2023-04-25 09:02:24.480 DEBUG (MainThread) [custom_components.tesla_custom.teslamate] MQTT Topic Recieved: teslamate/cars/2/display_name
2023-04-25 09:02:24.480 INFO (MainThread) [custom_components.tesla_custom.teslamate] Got display_name from MQTT for VIN:7SAYGDEE8PAxxxxxx | TeslsMateID:2
2023-04-25 09:02:24.503 DEBUG (MainThread) [custom_components.tesla_custom.teslamate] Got car ID. VIN:7SAYGDEE8PAxxxxxx TeslamateID: 2
2023-04-25 09:02:24.504 DEBUG (MainThread) [custom_components.tesla_custom.teslamate] MQTT Topic Recieved: teslamate/cars/2/est_battery_range_km
2023-04-25 09:02:24.504 INFO (MainThread) [custom_components.tesla_custom.teslamate] Got est_battery_range_km from MQTT for VIN:7SAYGDEE8PAxxxxxx | TeslsMateID:2
2023-04-25 09:02:24.504 DEBUG (MainThread) [custom_components.tesla_custom.teslamate] Got car ID. VIN:7SAYGDEE8PAxxxxxx TeslamateID: 2
2023-04-25 09:02:24.504 DEBUG (MainThread) [custom_components.tesla_custom.teslamate] MQTT Topic Recieved: teslamate/cars/2/exterior_color
2023-04-25 09:02:24.505 INFO (MainThread) [custom_components.tesla_custom.teslamate] Got exterior_color from MQTT for VIN:7SAYGDEE8PAxxxxxx | TeslsMateID:2
2023-04-25 09:02:24.513 DEBUG (MainThread) [custom_components.tesla_custom.teslamate] Got car ID. VIN:7SAYGDEE8PAxxxxxx TeslamateID: 2
2023-04-25 09:02:24.514 DEBUG (MainThread) [custom_components.tesla_custom.teslamate] MQTT Topic Recieved: teslamate/cars/2/trim_badging
2023-04-25 09:02:24.514 INFO (MainThread) [custom_components.tesla_custom.teslamate] Got trim_badging from MQTT for VIN:7SAYGDEE8PAxxxxxx | TeslsMateID:2
2023-04-25 09:02:24.514 DEBUG (MainThread) [custom_components.tesla_custom.teslamate] Got car ID. VIN:7SAYGDEE8PAxxxxxx TeslamateID: 2
2023-04-25 09:02:24.515 DEBUG (MainThread) [custom_components.tesla_custom.teslamate] MQTT Topic Recieved: teslamate/cars/2/wheel_type
2023-04-25 09:02:24.515 INFO (MainThread) [custom_components.tesla_custom.teslamate] Got wheel_type from MQTT for VIN:7SAYGDEE8PAxxxxxx | TeslsMateID:2
2023-04-25 09:02:24.515 DEBUG (MainThread) [custom_components.tesla_custom.teslamate] Got car ID. VIN:7SAYGDEE8PAxxxxxx TeslamateID: 2
2023-04-25 09:02:24.515 DEBUG (MainThread) [custom_components.tesla_custom.teslamate] MQTT Topic Recieved: teslamate/cars/2/healthy
2023-04-25 09:02:24.516 INFO (MainThread) [custom_components.tesla_custom.teslamate] Got healthy from MQTT for VIN:7SAYGDEE8PAxxxxxx | TeslsMateID:2
2023-04-25 09:02:24.516 DEBUG (MainThread) [custom_components.tesla_custom.teslamate] Got car ID. VIN:7SAYGDEE8PAxxxxxx TeslamateID: 2
2023-04-25 09:02:24.517 DEBUG (MainThread) [custom_components.tesla_custom.teslamate] MQTT Topic Recieved: teslamate/cars/2/latitude
2023-04-25 09:02:24.517 INFO (MainThread) [custom_components.tesla_custom.teslamate] Got latitude from MQTT for VIN:7SAYGDEE8PAxxxxxx | TeslsMateID:2
2023-04-25 09:02:24.518 DEBUG (MainThread) [custom_components.tesla_custom.teslamate] Updating drive_state for VIN:7SAYGDEE8PAxxxxxx
2023-04-25 09:02:24.528 DEBUG (MainThread) [custom_components.tesla_custom.teslamate] Got car ID. VIN:7SAYGDEE8PAxxxxxx TeslamateID: 2
2023-04-25 09:02:24.528 DEBUG (MainThread) [custom_components.tesla_custom.teslamate] MQTT Topic Recieved: teslamate/cars/2/spoiler_type
2023-04-25 09:02:24.528 INFO (MainThread) [custom_components.tesla_custom.teslamate] Got spoiler_type from MQTT for VIN:7SAYGDEE8PAxxxxxx | TeslsMateID:2
2023-04-25 09:02:24.535 DEBUG (MainThread) [custom_components.tesla_custom.teslamate] Got car ID. VIN:7SAYGDEE8PAxxxxxx TeslamateID: 2
2023-04-25 09:02:24.535 DEBUG (MainThread) [custom_components.tesla_custom.teslamate] MQTT Topic Recieved: teslamate/cars/2/since
2023-04-25 09:02:24.535 INFO (MainThread) [custom_components.tesla_custom.teslamate] Got since from MQTT for VIN:7SAYGDEE8PAxxxxxx | TeslsMateID:2
2023-04-25 09:02:24.539 DEBUG (MainThread) [custom_components.tesla_custom.teslamate] Got car ID. VIN:7SAYGDEE8PAxxxxxx TeslamateID: 2
2023-04-25 09:02:24.539 DEBUG (MainThread) [custom_components.tesla_custom.teslamate] MQTT Topic Recieved: teslamate/cars/2/model
2023-04-25 09:02:24.539 INFO (MainThread) [custom_components.tesla_custom.teslamate] Got model from MQTT for VIN:7SAYGDEE8PAxxxxxx | TeslsMateID:2
2023-04-25 09:02:24.539 DEBUG (MainThread) [custom_components.tesla_custom.teslamate] Got car ID. VIN:7SAYGDEE8PAxxxxxx TeslamateID: 2
2023-04-25 09:02:24.539 DEBUG (MainThread) [custom_components.tesla_custom.teslamate] MQTT Topic Recieved: teslamate/cars/2/odometer
2023-04-25 09:02:24.540 INFO (MainThread) [custom_components.tesla_custom.teslamate] Got odometer from MQTT for VIN:7SAYGDEE8PAxxxxxx | TeslsMateID:2
2023-04-25 09:02:24.540 DEBUG (MainThread) [custom_components.tesla_custom.teslamate] Updating vehicle_state for VIN:7SAYGDEE8PAxxxxxx
2023-04-25 09:02:24.551 DEBUG (MainThread) [custom_components.tesla_custom.teslamate] Got car ID. VIN:7SAYGDEE8PAxxxxxx TeslamateID: 2
2023-04-25 09:02:24.551 DEBUG (MainThread) [custom_components.tesla_custom.teslamate] MQTT Topic Recieved: teslamate/cars/2/state
2023-04-25 09:02:24.551 INFO (MainThread) [custom_components.tesla_custom.teslamate] Got state from MQTT for VIN:7SAYGDEE8PAxxxxxx | TeslsMateID:2
2023-04-25 09:02:24.551 DEBUG (MainThread) [custom_components.tesla_custom.teslamate] Got car ID. VIN:7SAYGDEE8PAxxxxxx TeslamateID: 2
2023-04-25 09:02:24.552 DEBUG (MainThread) [custom_components.tesla_custom.teslamate] MQTT Topic Recieved: teslamate/cars/2/ideal_battery_range_km
2023-04-25 09:02:24.552 INFO (MainThread) [custom_components.tesla_custom.teslamate] Got ideal_battery_range_km from MQTT for VIN:7SAYGDEE8PAxxxxxx | TeslsMateID:2
2023-04-25 09:02:24.563 DEBUG (MainThread) [custom_components.tesla_custom.teslamate] Got car ID. VIN:7SAYGDEE8PAxxxxxx TeslamateID: 2
2023-04-25 09:02:24.563 DEBUG (MainThread) [custom_components.tesla_custom.teslamate] MQTT Topic Recieved: teslamate/cars/2/version
2023-04-25 09:02:24.563 INFO (MainThread) [custom_components.tesla_custom.teslamate] Got version from MQTT for VIN:7SAYGDEE8PAxxxxxx | TeslsMateID:2
2023-04-25 09:02:24.564 DEBUG (MainThread) [custom_components.tesla_custom.teslamate] Got car ID. VIN:7SAYGDEE8PAxxxxxx TeslamateID: 2
2023-04-25 09:02:24.564 DEBUG (MainThread) [custom_components.tesla_custom.teslamate] MQTT Topic Recieved: teslamate/cars/2/battery_level
2023-04-25 09:02:24.564 INFO (MainThread) [custom_components.tesla_custom.teslamate] Got battery_level from MQTT for VIN:7SAYGDEE8PAxxxxxx | TeslsMateID:2
2023-04-25 09:02:24.565 DEBUG (MainThread) [custom_components.tesla_custom.teslamate] Updating charge_state for VIN:7SAYGDEE8PAxxxxxx
2023-04-25 09:02:24.575 DEBUG (MainThread) [custom_components.tesla_custom.teslamate] Got car ID. VIN:7SAYGDEE8PAxxxxxx TeslamateID: 2
2023-04-25 09:02:24.575 DEBUG (MainThread) [custom_components.tesla_custom.teslamate] MQTT Topic Recieved: teslamate/cars/2/longitude
2023-04-25 09:02:24.575 INFO (MainThread) [custom_components.tesla_custom.teslamate] Got longitude from MQTT for VIN:7SAYGDEE8PAxxxxxx | TeslsMateID:2
2023-04-25 09:02:24.575 DEBUG (MainThread) [custom_components.tesla_custom.teslamate] Updating drive_state for VIN:7SAYGDEE8PAxxxxxx
2023-04-25 09:02:24.593 DEBUG (MainThread) [custom_components.tesla_custom.teslamate] Got car ID. VIN:7SAYGDEE8PAxxxxxx TeslamateID: 2
2023-04-25 09:02:24.593 DEBUG (MainThread) [custom_components.tesla_custom.teslamate] MQTT Topic Recieved: teslamate/cars/2/usable_battery_level
2023-04-25 09:02:24.593 INFO (MainThread) [custom_components.tesla_custom.teslamate] Got usable_battery_level from MQTT for VIN:7SAYGDEE8PAxxxxxx | TeslsMateID:2
2023-04-25 09:02:24.593 DEBUG (MainThread) [custom_components.tesla_custom.teslamate] Updating charge_state for VIN:7SAYGDEE8PAxxxxxx
2023-04-25 09:02:24.605 DEBUG (MainThread) [custom_components.tesla_custom.teslamate] Got car ID. VIN:7SAYGDEE8PAxxxxxx TeslamateID: 2
2023-04-25 09:02:24.605 DEBUG (MainThread) [custom_components.tesla_custom.teslamate] MQTT Topic Recieved: teslamate/cars/2/outside_temp
2023-04-25 09:02:24.605 INFO (MainThread) [custom_components.tesla_custom.teslamate] Got outside_temp from MQTT for VIN:7SAYGDEE8PAxxxxxx | TeslsMateID:2
2023-04-25 09:02:24.606 DEBUG (MainThread) [custom_components.tesla_custom.teslamate] Updating climate_state for VIN:7SAYGDEE8PAxxxxxx
2023-04-25 09:02:24.618 DEBUG (MainThread) [custom_components.tesla_custom.teslamate] Got car ID. VIN:7SAYGDEE8PAxxxxxx TeslamateID: 2
2023-04-25 09:02:24.618 DEBUG (MainThread) [custom_components.tesla_custom.teslamate] MQTT Topic Recieved: teslamate/cars/2/geofence
2023-04-25 09:02:24.618 INFO (MainThread) [custom_components.tesla_custom.teslamate] Got geofence from MQTT for VIN:7SAYGDEE8PAxxxxxx | TeslsMateID:2
2023-04-25 09:02:24.640 DEBUG (MainThread) [custom_components.tesla_custom.teslamate] Got car ID. VIN:7SAYGDEE8PAxxxxxx TeslamateID: 2
2023-04-25 09:02:24.640 DEBUG (MainThread) [custom_components.tesla_custom.teslamate] MQTT Topic Recieved: teslamate/cars/2/inside_temp
2023-04-25 09:02:24.640 INFO (MainThread) [custom_components.tesla_custom.teslamate] Got inside_temp from MQTT for VIN:7SAYGDEE8PAxxxxxx | TeslsMateID:2
2023-04-25 09:02:24.640 DEBUG (MainThread) [custom_components.tesla_custom.teslamate] Updating climate_state for VIN:7SAYGDEE8PAxxxxxx
2023-04-25 09:02:24.652 DEBUG (MainThread) [custom_components.tesla_custom.teslamate] Got car ID. VIN:7SAYGDEE8PAxxxxxx TeslamateID: 2
2023-04-25 09:02:24.652 DEBUG (MainThread) [custom_components.tesla_custom.teslamate] MQTT Topic Recieved: teslamate/cars/2/tpms_pressure_rl
2023-04-25 09:02:24.653 INFO (MainThread) [custom_components.tesla_custom.teslamate] Got tpms_pressure_rl from MQTT for VIN:7SAYGDEE8PAxxxxxx | TeslsMateID:2
2023-04-25 09:02:24.653 DEBUG (MainThread) [custom_components.tesla_custom.teslamate] Updating vehicle_state for VIN:7SAYGDEE8PAxxxxxx
2023-04-25 09:02:24.662 DEBUG (MainThread) [custom_components.tesla_custom.teslamate] Got car ID. VIN:7SAYGDEE8PAxxxxxx TeslamateID: 2
2023-04-25 09:02:24.662 DEBUG (MainThread) [custom_components.tesla_custom.teslamate] MQTT Topic Recieved: teslamate/cars/2/trunk_open
2023-04-25 09:02:24.662 INFO (MainThread) [custom_components.tesla_custom.teslamate] Got trunk_open from MQTT for VIN:7SAYGDEE8PAxxxxxx | TeslsMateID:2
2023-04-25 09:02:24.663 DEBUG (MainThread) [custom_components.tesla_custom.teslamate] Got car ID. VIN:7SAYGDEE8PAxxxxxx TeslamateID: 2
2023-04-25 09:02:24.663 DEBUG (MainThread) [custom_components.tesla_custom.teslamate] MQTT Topic Recieved: teslamate/cars/2/charge_current_request_max
2023-04-25 09:02:24.663 INFO (MainThread) [custom_components.tesla_custom.teslamate] Got charge_current_request_max from MQTT for VIN:7SAYGDEE8PAxxxxxx | TeslsMateID:2
2023-04-25 09:02:24.666 DEBUG (MainThread) [custom_components.tesla_custom.teslamate] Got car ID. VIN:7SAYGDEE8PAxxxxxx TeslamateID: 2
2023-04-25 09:02:24.666 DEBUG (MainThread) [custom_components.tesla_custom.teslamate] MQTT Topic Recieved: teslamate/cars/2/tpms_pressure_fr
2023-04-25 09:02:24.666 INFO (MainThread) [custom_components.tesla_custom.teslamate] Got tpms_pressure_fr from MQTT for VIN:7SAYGDEE8PAxxxxxx | TeslsMateID:2
2023-04-25 09:02:24.666 DEBUG (MainThread) [custom_components.tesla_custom.teslamate] Updating vehicle_state for VIN:7SAYGDEE8PAxxxxxx
2023-04-25 09:02:24.675 DEBUG (MainThread) [custom_components.tesla_custom.teslamate] Got car ID. VIN:7SAYGDEE8PAxxxxxx TeslamateID: 2
2023-04-25 09:02:24.675 DEBUG (MainThread) [custom_components.tesla_custom.teslamate] MQTT Topic Recieved: teslamate/cars/2/power
2023-04-25 09:02:24.675 INFO (MainThread) [custom_components.tesla_custom.teslamate] Got power from MQTT for VIN:7SAYGDEE8PAxxxxxx | TeslsMateID:2
2023-04-25 09:02:24.675 DEBUG (MainThread) [custom_components.tesla_custom.teslamate] Got car ID. VIN:7SAYGDEE8PAxxxxxx TeslamateID: 2
2023-04-25 09:02:24.675 DEBUG (MainThread) [custom_components.tesla_custom.teslamate] MQTT Topic Recieved: teslamate/cars/2/charger_actual_current
2023-04-25 09:02:24.675 INFO (MainThread) [custom_components.tesla_custom.teslamate] Got charger_actual_current from MQTT for VIN:7SAYGDEE8PAxxxxxx | TeslsMateID:2
2023-04-25 09:02:24.676 DEBUG (MainThread) [custom_components.tesla_custom.teslamate] Updating charge_state for VIN:7SAYGDEE8PAxxxxxx
2023-04-25 09:02:24.685 DEBUG (MainThread) [custom_components.tesla_custom.teslamate] Got car ID. VIN:7SAYGDEE8PAxxxxxx TeslamateID: 2
2023-04-25 09:02:24.685 DEBUG (MainThread) [custom_components.tesla_custom.teslamate] MQTT Topic Recieved: teslamate/cars/2/doors_open
2023-04-25 09:02:24.685 INFO (MainThread) [custom_components.tesla_custom.teslamate] Got doors_open from MQTT for VIN:7SAYGDEE8PAxxxxxx | TeslsMateID:2
2023-04-25 09:02:24.690 DEBUG (MainThread) [custom_components.tesla_custom.teslamate] Got car ID. VIN:7SAYGDEE8PAxxxxxx TeslamateID: 2
2023-04-25 09:02:24.690 DEBUG (MainThread) [custom_components.tesla_custom.teslamate] MQTT Topic Recieved: teslamate/cars/2/time_to_full_charge
2023-04-25 09:02:24.690 INFO (MainThread) [custom_components.tesla_custom.teslamate] Got time_to_full_charge from MQTT for VIN:7SAYGDEE8PAxxxxxx | TeslsMateID:2
2023-04-25 09:02:24.690 DEBUG (MainThread) [custom_components.tesla_custom.teslamate] Updating charge_state for VIN:7SAYGDEE8PAxxxxxx
2023-04-25 09:02:24.701 DEBUG (MainThread) [custom_components.tesla_custom.teslamate] Got car ID. VIN:7SAYGDEE8PAxxxxxx TeslamateID: 2
2023-04-25 09:02:24.701 DEBUG (MainThread) [custom_components.tesla_custom.teslamate] MQTT Topic Recieved: teslamate/cars/2/is_preconditioning
2023-04-25 09:02:24.701 INFO (MainThread) [custom_components.tesla_custom.teslamate] Got is_preconditioning from MQTT for VIN:7SAYGDEE8PAxxxxxx | TeslsMateID:2
2023-04-25 09:02:24.701 DEBUG (MainThread) [custom_components.tesla_custom.teslamate] Got car ID. VIN:7SAYGDEE8PAxxxxxx TeslamateID: 2
2023-04-25 09:02:24.701 DEBUG (MainThread) [custom_components.tesla_custom.teslamate] MQTT Topic Recieved: teslamate/cars/2/sentry_mode
2023-04-25 09:02:24.702 INFO (MainThread) [custom_components.tesla_custom.teslamate] Got sentry_mode from MQTT for VIN:7SAYGDEE8PAxxxxxx | TeslsMateID:2
2023-04-25 09:02:24.702 DEBUG (MainThread) [custom_components.tesla_custom.teslamate] Updating vehicle_state for VIN:7SAYGDEE8PAxxxxxx
2023-04-25 09:02:24.714 DEBUG (MainThread) [custom_components.tesla_custom.teslamate] Got car ID. VIN:7SAYGDEE8PAxxxxxx TeslamateID: 2
2023-04-25 09:02:24.714 DEBUG (MainThread) [custom_components.tesla_custom.teslamate] MQTT Topic Recieved: teslamate/cars/2/update_available
2023-04-25 09:02:24.714 INFO (MainThread) [custom_components.tesla_custom.teslamate] Got update_available from MQTT for VIN:7SAYGDEE8PAxxxxxx | TeslsMateID:2
2023-04-25 09:02:24.715 DEBUG (MainThread) [custom_components.tesla_custom.teslamate] Got car ID. VIN:7SAYGDEE8PAxxxxxx TeslamateID: 2
2023-04-25 09:02:24.715 DEBUG (MainThread) [custom_components.tesla_custom.teslamate] MQTT Topic Recieved: teslamate/cars/2/charger_voltage
2023-04-25 09:02:24.715 INFO (MainThread) [custom_components.tesla_custom.teslamate] Got charger_voltage from MQTT for VIN:7SAYGDEE8PAxxxxxx | TeslsMateID:2
2023-04-25 09:02:24.715 DEBUG (MainThread) [custom_components.tesla_custom.teslamate] Updating charge_state for VIN:7SAYGDEE8PAxxxxxx
2023-04-25 09:02:24.731 DEBUG (MainThread) [custom_components.tesla_custom.teslamate] Got car ID. VIN:7SAYGDEE8PAxxxxxx TeslamateID: 2
2023-04-25 09:02:24.732 DEBUG (MainThread) [custom_components.tesla_custom.teslamate] MQTT Topic Recieved: teslamate/cars/2/charge_limit_soc
2023-04-25 09:02:24.732 INFO (MainThread) [custom_components.tesla_custom.teslamate] Got charge_limit_soc from MQTT for VIN:7SAYGDEE8PAxxxxxx | TeslsMateID:2
2023-04-25 09:02:24.732 DEBUG (MainThread) [custom_components.tesla_custom.teslamate] Updating charge_state for VIN:7SAYGDEE8PAxxxxxx
2023-04-25 09:02:24.750 DEBUG (MainThread) [custom_components.tesla_custom.teslamate] Got car ID. VIN:7SAYGDEE8PAxxxxxx TeslamateID: 2
2023-04-25 09:02:24.750 DEBUG (MainThread) [custom_components.tesla_custom.teslamate] MQTT Topic Recieved: teslamate/cars/2/windows_open
2023-04-25 09:02:24.750 INFO (MainThread) [custom_components.tesla_custom.teslamate] Got windows_open from MQTT for VIN:7SAYGDEE8PAxxxxxx | TeslsMateID:2
2023-04-25 09:02:24.750 DEBUG (MainThread) [custom_components.tesla_custom.teslamate] Got car ID. VIN:7SAYGDEE8PAxxxxxx TeslamateID: 2
2023-04-25 09:02:24.750 DEBUG (MainThread) [custom_components.tesla_custom.teslamate] MQTT Topic Recieved: teslamate/cars/2/is_user_present
2023-04-25 09:02:24.750 INFO (MainThread) [custom_components.tesla_custom.teslamate] Got is_user_present from MQTT for VIN:7SAYGDEE8PAxxxxxx | TeslsMateID:2
2023-04-25 09:02:24.769 DEBUG (MainThread) [custom_components.tesla_custom.teslamate] Got car ID. VIN:7SAYGDEE8PAxxxxxx TeslamateID: 2
2023-04-25 09:02:24.769 DEBUG (MainThread) [custom_components.tesla_custom.teslamate] MQTT Topic Recieved: teslamate/cars/2/heading
2023-04-25 09:02:24.769 INFO (MainThread) [custom_components.tesla_custom.teslamate] Got heading from MQTT for VIN:7SAYGDEE8PAxxxxxx | TeslsMateID:2
2023-04-25 09:02:24.769 DEBUG (MainThread) [custom_components.tesla_custom.teslamate] Updating drive_state for VIN:7SAYGDEE8PAxxxxxx
2023-04-25 09:02:24.778 DEBUG (MainThread) [custom_components.tesla_custom.teslamate] Got car ID. VIN:7SAYGDEE8PAxxxxxx TeslamateID: 2
2023-04-25 09:02:24.779 DEBUG (MainThread) [custom_components.tesla_custom.teslamate] MQTT Topic Recieved: teslamate/cars/2/locked
2023-04-25 09:02:24.779 INFO (MainThread) [custom_components.tesla_custom.teslamate] Got locked from MQTT for VIN:7SAYGDEE8PAxxxxxx | TeslsMateID:2
2023-04-25 09:02:24.779 DEBUG (MainThread) [custom_components.tesla_custom.teslamate] Updating vehicle_state for VIN:7SAYGDEE8PAxxxxxx
2023-04-25 09:02:24.789 DEBUG (MainThread) [custom_components.tesla_custom.teslamate] Got car ID. VIN:7SAYGDEE8PAxxxxxx TeslamateID: 2
2023-04-25 09:02:24.789 DEBUG (MainThread) [custom_components.tesla_custom.teslamate] MQTT Topic Recieved: teslamate/cars/2/charge_energy_added
2023-04-25 09:02:24.789 INFO (MainThread) [custom_components.tesla_custom.teslamate] Got charge_energy_added from MQTT for VIN:7SAYGDEE8PAxxxxxx | TeslsMateID:2
2023-04-25 09:02:24.789 DEBUG (MainThread) [custom_components.tesla_custom.teslamate] Updating charge_state for VIN:7SAYGDEE8PAxxxxxx
2023-04-25 09:02:24.799 DEBUG (MainThread) [custom_components.tesla_custom.teslamate] Got car ID. VIN:7SAYGDEE8PAxxxxxx TeslamateID: 2
2023-04-25 09:02:24.800 DEBUG (MainThread) [custom_components.tesla_custom.teslamate] MQTT Topic Recieved: teslamate/cars/2/tpms_pressure_rr
2023-04-25 09:02:24.800 INFO (MainThread) [custom_components.tesla_custom.teslamate] Got tpms_pressure_rr from MQTT for VIN:7SAYGDEE8PAxxxxxx | TeslsMateID:2
2023-04-25 09:02:24.800 DEBUG (MainThread) [custom_components.tesla_custom.teslamate] Updating vehicle_state for VIN:7SAYGDEE8PAxxxxxx
2023-04-25 09:02:24.808 DEBUG (MainThread) [custom_components.tesla_custom.teslamate] Got car ID. VIN:7SAYGDEE8PAxxxxxx TeslamateID: 2
2023-04-25 09:02:24.809 DEBUG (MainThread) [custom_components.tesla_custom.teslamate] MQTT Topic Recieved: teslamate/cars/2/plugged_in
2023-04-25 09:02:24.809 INFO (MainThread) [custom_components.tesla_custom.teslamate] Got plugged_in from MQTT for VIN:7SAYGDEE8PAxxxxxx | TeslsMateID:2
2023-04-25 09:02:24.809 DEBUG (MainThread) [custom_components.tesla_custom.teslamate] Got car ID. VIN:7SAYGDEE8PAxxxxxx TeslamateID: 2
2023-04-25 09:02:24.809 DEBUG (MainThread) [custom_components.tesla_custom.teslamate] MQTT Topic Recieved: teslamate/cars/2/frunk_open
2023-04-25 09:02:24.809 INFO (MainThread) [custom_components.tesla_custom.teslamate] Got frunk_open from MQTT for VIN:7SAYGDEE8PAxxxxxx | TeslsMateID:2
2023-04-25 09:02:24.814 DEBUG (MainThread) [custom_components.tesla_custom.teslamate] Got car ID. VIN:7SAYGDEE8PAxxxxxx TeslamateID: 2
2023-04-25 09:02:24.814 DEBUG (MainThread) [custom_components.tesla_custom.teslamate] MQTT Topic Recieved: teslamate/cars/2/charge_current_request
2023-04-25 09:02:24.814 INFO (MainThread) [custom_components.tesla_custom.teslamate] Got charge_current_request from MQTT for VIN:7SAYGDEE8PAxxxxxx | TeslsMateID:2
2023-04-25 09:02:24.815 DEBUG (MainThread) [custom_components.tesla_custom.teslamate] Got car ID. VIN:7SAYGDEE8PAxxxxxx TeslamateID: 2
2023-04-25 09:02:24.815 DEBUG (MainThread) [custom_components.tesla_custom.teslamate] MQTT Topic Recieved: teslamate/cars/2/tpms_pressure_fl
2023-04-25 09:02:24.815 INFO (MainThread) [custom_components.tesla_custom.teslamate] Got tpms_pressure_fl from MQTT for VIN:7SAYGDEE8PAxxxxxx | TeslsMateID:2
2023-04-25 09:02:24.815 DEBUG (MainThread) [custom_components.tesla_custom.teslamate] Updating vehicle_state for VIN:7SAYGDEE8PAxxxxxx
2023-04-25 09:02:24.824 DEBUG (MainThread) [custom_components.tesla_custom.teslamate] Got car ID. VIN:7SAYGDEE8PAxxxxxx TeslamateID: 2
2023-04-25 09:02:24.824 DEBUG (MainThread) [custom_components.tesla_custom.teslamate] MQTT Topic Recieved: teslamate/cars/2/charger_power
2023-04-25 09:02:24.825 INFO (MainThread) [custom_components.tesla_custom.teslamate] Got charger_power from MQTT for VIN:7SAYGDEE8PAxxxxxx | TeslsMateID:2
2023-04-25 09:02:24.825 DEBUG (MainThread) [custom_components.tesla_custom.teslamate] Updating charge_state for VIN:7SAYGDEE8PAxxxxxx
2023-04-25 09:02:24.833 DEBUG (MainThread) [custom_components.tesla_custom.teslamate] Got car ID. VIN:7SAYGDEE8PAxxxxxx TeslamateID: 2
2023-04-25 09:02:24.833 DEBUG (MainThread) [custom_components.tesla_custom.teslamate] MQTT Topic Recieved: teslamate/cars/2/is_climate_on
2023-04-25 09:02:24.833 INFO (MainThread) [custom_components.tesla_custom.teslamate] Got is_climate_on from MQTT for VIN:7SAYGDEE8PAxxxxxx | TeslsMateID:2
2023-04-25 09:02:24.834 DEBUG (MainThread) [custom_components.tesla_custom.teslamate] Updating climate_state for VIN:7SAYGDEE8PAxxxxxx
2023-04-25 09:02:24.843 DEBUG (MainThread) [custom_components.tesla_custom.teslamate] Got car ID. VIN:7SAYGDEE8PAxxxxxx TeslamateID: 2
2023-04-25 09:02:24.844 DEBUG (MainThread) [custom_components.tesla_custom.teslamate] MQTT Topic Recieved: teslamate/cars/2/charge_port_door_open
2023-04-25 09:02:24.844 INFO (MainThread) [custom_components.tesla_custom.teslamate] Got charge_port_door_open from MQTT for VIN:7SAYGDEE8PAxxxxxx | TeslsMateID:2
2023-04-25 09:02:24.844 DEBUG (MainThread) [custom_components.tesla_custom.teslamate] Got car ID. VIN:7SAYGDEE8PAxxxxxx TeslamateID: 2
2023-04-25 09:02:24.844 DEBUG (MainThread) [custom_components.tesla_custom.teslamate] MQTT Topic Recieved: teslamate/cars/2/speed
2023-04-25 09:02:24.844 INFO (MainThread) [custom_components.tesla_custom.teslamate] Got speed from MQTT for VIN:7SAYGDEE8PAxxxxxx | TeslsMateID:2
2023-04-25 09:02:24.844 DEBUG (MainThread) [custom_components.tesla_custom.teslamate] Updating drive_state for VIN:7SAYGDEE8PAxxxxxx
2023-04-25 09:02:24.854 DEBUG (MainThread) [custom_components.tesla_custom.teslamate] Got car ID. VIN:7SAYGDEE8PAxxxxxx TeslamateID: 2
2023-04-25 09:02:24.854 DEBUG (MainThread) [custom_components.tesla_custom.teslamate] MQTT Topic Recieved: teslamate/cars/2/elevation
2023-04-25 09:02:24.854 INFO (MainThread) [custom_components.tesla_custom.teslamate] Got elevation from MQTT for VIN:7SAYGDEE8PAxxxxxx | TeslsMateID:2
```

**Comment by drjjr2** [comment]
Just took car 1 out for a drive and no log entries. I know Teslamate is updating MQTT on teslamate/cars/1 because the location sensor I have manually configured is allowing me to automatically open/close the garage door.

My log is filled with:
```
2023-04-25 09:12:57.278 DEBUG (MainThread) [custom_components.tesla_custom] Running controller.update()
2023-04-25 09:12:57.279 DEBUG (MainThread) [custom_components.tesla_custom] Finished fetching tesla_custom data in 0.001 seconds (success: True)
2023-04-25 09:12:57.469 DEBUG (MainThread) [custom_components.tesla_custom] Running controller.update()
2023-04-25 09:12:57.471 DEBUG (MainThread) [custom_components.tesla_custom] Finished fetching tesla_custom data in 0.001 seconds (success: True)
2023-04-25 09:13:07.251 DEBUG (MainThread) [custom_components.tesla_custom] Running controller.update()
2023-04-25 09:13:07.252 DEBUG (MainThread) [custom_components.tesla_custom] Finished fetching tesla_custom data in 0.001 seconds (success: True)
2023-04-25 09:13:07.472 DEBUG (MainThread) [custom_components.tesla_custom] Running controller.update()
2023-04-25 09:13:07.472 DEBUG (MainThread) [custom_components.tesla_custom] Finished fetching tesla_custom data in 0.001 seconds (success: True)
```

**Comment by Megabytemb** [comment]
Those logs helped a bunch

Can you try this new version of the teslamate.py?
https://github.com/Megabytemb/tesla/blob/telslamate_updates/custom_components/tesla_custom/teslamate.py

I was doing the MQTT sub state handing wrong, and I think I've fixed it

**Comment by drjjr2** [comment]
That seemed to do it! At least as far as I can tell from the logs. Still seeing this on startup (now for both cars) but I think I read you had a fix for it as well:

```
2023-04-26 07:11:57.143 ERROR (SyncWorker_12) [homeassistant.util.logging] Exception in msg_recieved when handling msg on 'teslamate/cars/1/odometer': '5593.91'
Traceback (most recent call last):
  File "/config/custom_components/tesla_custom/teslamate.py", line 262, in msg_recieved
    ).result()
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 458, in result
    return self.__get_result()
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/config/custom_components/tesla_custom/teslamate.py", line 305, in async_handle_new_data
    coordinator.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 142, in async_update_listeners
    update_callback()
  File "/config/custom_components/tesla_custom/base.py", line 40, in refresh
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 568, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 632, in _async_write_ha_state
    state = self._stringify_state(available)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 574, in _stringify_state
    if (state := self.state) is None:
  File "/usr/src/homeassistant/homeassistant/components/select/__init__.py", line 147, in state
    if self.current_option is None or self.current_option not in self.options:
  File "/config/custom_components/tesla_custom/select.py", line 156, in current_option
    current_value = self._car.get_seat_heater_status(
  File "/usr/local/lib/python3.10/site-packages/teslajsonpy/car.py", line 877, in get_seat_heater_status
    return self._vehicle_data.get("climate_state").get(seat_id)
AttributeError: 'NoneType' object has no attribute 'get'

2023-04-26 07:11:57.152 ERROR (SyncWorker_15) [homeassistant.util.logging] Exception in msg_recieved when handling msg on 'teslamate/cars/1/usable_battery_level': '80'
Traceback (most recent call last):
  File "/config/custom_components/tesla_custom/teslamate.py", line 262, in msg_recieved
    ).result()
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 458, in result
    return self.__get_result()
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/config/custom_components/tesla_custom/teslamate.py", line 315, in async_handle_new_data
    coordinator.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 142, in async_update_listeners
    update_callback()
  File "/config/custom_components/tesla_custom/base.py", line 40, in refresh
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 568, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 632, in _async_write_ha_state
    state = self._stringify_state(available)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 574, in _stringify_state
    if (state := self.state) is None:
  File "/usr/src/homeassistant/homeassistant/components/select/__init__.py", line 147, in state
    if self.current_option is None or self.current_option not in self.options:
  File "/config/custom_components/tesla_custom/select.py", line 156, in current_option
    current_value = self._car.get_seat_heater_status(
  File "/usr/local/lib/python3.10/site-packages/teslajsonpy/car.py", line 877, in get_seat_heater_status
    return self._vehicle_data.get("climate_state").get(seat_id)
AttributeError: 'NoneType' object has no attribute 'get'

2023-04-26 07:11:57.154 DEBUG (MainThread) [custom_components.tesla_custom.teslamate] MQTT Topic Recieved: teslamate/cars/2/locked
2023-04-26 07:11:57.155 DEBUG (MainThread) [custom_components.tesla_custom.teslamate] Getting TeslaCar for teslaMateID:2
2023-04-26 07:11:57.155 INFO (MainThread) [custom_components.tesla_custom.teslamate] Got locked from MQTT for VIN:7SAYGDEE8PA070531 | TeslsMateID:2
2023-04-26 07:11:57.155 DEBUG (MainThread) [custom_components.tesla_custom.teslamate] Updating vehicle_state for VIN:7SAYGDEE8PA070531
2023-04-26 07:11:57.164 ERROR (SyncWorker_11) [homeassistant.util.logging] Exception in msg_recieved when handling msg on 'teslamate/cars/1/longitude': '-95.591381'
Traceback (most recent call last):
  File "/config/custom_components/tesla_custom/teslamate.py", line 262, in msg_recieved
    ).result()
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 458, in result
    return self.__get_result()
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/config/custom_components/tesla_custom/teslamate.py", line 300, in async_handle_new_data
    coordinator.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 142, in async_update_listeners
    update_callback()
  File "/config/custom_components/tesla_custom/base.py", line 40, in refresh
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 568, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 632, in _async_write_ha_state
    state = self._stringify_state(available)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 574, in _stringify_state
    if (state := self.state) is None:
  File "/usr/src/homeassistant/homeassistant/components/select/__init__.py", line 147, in state
    if self.current_option is None or self.current_option not in self.options:
  File "/config/custom_components/tesla_custom/select.py", line 156, in current_option
    current_value = self._car.get_seat_heater_status(
  File "/usr/local/lib/python3.10/site-packages/teslajsonpy/car.py", line 877, in get_seat_heater_status
    return self._vehicle_data.get("climate_state").get(seat_id)
AttributeError: 'NoneType' object has no attribute 'get'
```
